# Generated by Django 4.1.5 on 2023-02-07 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanage', '0002_alter_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='user_id',
        ),
    ]
