# Generated by Django 4.1.5 on 2023-02-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanage', '0003_rename_user_task_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-task_created_at']},
        ),
    ]
