# Generated by Django 4.1.5 on 2023-04-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanage', '0006_alter_subtask_subtask_status_alter_task_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='subtask_status',
            field=models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('cancelled', 'Cancelled')], default='To Do', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('cancelled', 'Cancelled')], default='todo', max_length=100),
        ),
    ]
